#!/usr/bin/env python3

# sudo apt install python3-smbus i2c-tools
# make sure the I2C interface is enabled in raspi-config
# copy this script to $home/bin and make it executable

from smbus import SMBus
from struct import unpack
from time import sleep


bus = SMBus(1)
bus.write_byte(20, 10)
sleep(0.0001)
byte_list = [bus.read_byte(20) for _ in range(2)]
millivolts = unpack("H", bytes(byte_list))[0]
print(millivolts, "millivolts")

